products = [
    {
        'image': "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        'name': "Nike Air Monarch IV",
        'price': 200,
        'brand': "Nike",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        'name': "Nike Air Vapormax Plus",
        'price': 200,
        'brand': "Nike",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
        'name': "Nike Waffle One Sneaker",
        'price': 200,
        'brand': "Nike",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
        'name': "Nike Running Shoe",
        'price': 200,
        'brand': "Adidas",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
        'name': "Flat Slip On Pumps",
        'price': 200,
        'brand': "Vans",
        'category': "flats",
    },
    {
        'image': "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
        'name': "Knit Ballet Flat",
        'price': 50,
        'brand': "Adidas",
        'category': "flats",
    },
    {
        'image': "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
        'name': "Loafer Flats",
        'price': 50,
        'brand': "Vans",
        'category': "flats",
    },
    {
        'image': "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
        'name': "Nike Zoom Freak",
        'price': 200,
        'brand': "Nike",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
        'name': "Nike Men's Sneaker",
        'price': 200,
        'brand': "Adidas",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        'name': "PUMA BLACK-OCE",
        'price': 150,
        'brand': "Puma",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
        'name': "Pacer Future Sneaker",
        'price': 150,
        'brand': "Puma",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
        'name': "Unisex-Adult Super",
        'price': 150,
        'brand': "Puma",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
        'name': "Roma Basic Sneaker",
        'price': 150,
        'brand': "Puma",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
        'name': "Pacer Future Doubleknit",
        'price': 150,
        'brand': "Puma",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        'name': "Fusion Evo Golf Shoe",
        'price': 100,
        'brand': "Puma",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
        'name': "Rainbow Chex Skate",
        'price': 100,
        'brand': "Vans",
        'category': "flats",
    },
    {
        'image': "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
        'name': "Low-Top Trainers",
        'price': 100,
        'brand': "Vans",
        'category': "sandals",
    },
    {
        'image': "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
        'name': "Vans Unisex Low-Top",
        'price': 100,
        'brand': "Vans",
        'category': "sandals",
    },
    {
        'image': "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
        'name': "Classic Bandana Sneakers",
        'price': 50,
        'brand': "Nike",
        'category': "sandals",
    },
    {
        'image': "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
        'name': "Chunky High Heel",
        'price': 50,
        'brand': "Vans",
        'category': "heels",
    },
    {
        'image': "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
        'name': "Slip On Stiletto High Heel",
        'price': 100,
        'brand': "Puma",
        'category': "heels",
    },
    {
        'image': "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
        'name': "DREAM PAIRS Court Shoes",
        'price': 150,
        'brand': "Nike",
        'category': "heels",
    },
    {
        'image': "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        'name': "Nike Air Vapormax Plus",
        'price': 200,
        'brand': "Nike",
        'category': "sneakers",
    },
    {
        'image': "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
        'name': "Low Mid Block Heels",
        'price': 200,
        'brand': "Nike",
        'category': "heels",
    },
    {
        'image': "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
        'name': "Chunky High Heel",
        'price': 50,
        'brand': "Adidas",
        'category': "heels",
    },
    {
        'image': "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
        'name': "Amore Fashion Stilettos",
        'price': 150,
        'brand': "Adidas",
        'category': "heels",
    },
    {
        'image': "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
        'name': "Bridal Sandals Glitter",
        'price': 50,
        'brand': "Adidas",
        'category': "heels",
    },
    {
        'image': "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
        'name': "Wedding Prom Bridal",
        'price': 50,
        'brand': "Adidas",
        'category': "flats",
    },
]
